"""Add test and media

Revision ID: cd7109b32475
Revises: 82e911ca8252
Create Date: 2023-12-11 03:30:21.257041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd7109b32475'
down_revision: Union[str, None] = '82e911ca8252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('type', sa.VARCHAR(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('duration', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('completed_exercise', sa.Column('completed_at', sa.TIMESTAMP(), nullable=True))
    op.drop_column('completed_exercise', 'competed_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('completed_exercise', sa.Column('competed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('completed_exercise', 'completed_at')
    op.drop_table('test')
    op.drop_table('media')
    # ### end Alembic commands ###
